# Generated by Django 2.2.6 on 2021-06-07 08:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0015_follow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='author',
        ),
        migrations.AddField(
            model_name='follow',
            name='author',
            field=models.ManyToManyField(help_text='Тот, на кого подписан', related_name='following', to=settings.AUTH_USER_MODEL, verbose_name='Подписан'),
        ),
    ]
